version: 2.1

orbs:
  android: circleci/android@2.1.2

jobs:
  run-ui-tests:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          system-image: system-images;android-30;default;x86

workflows:
  android-ci:
    jobs:
      - run-ui-tests