version: 2.1

orbs:
  android: circleci/android@2.1.2

jobs:
  run-ui-tests:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2022.06.2
    steps:
      - checkout
      - android/create-avd:
          avd-name: android-ci-avd
          system-image: system-images;android-31;default;x86_64
          install: true
      - android/start-emulator:
          avd-name: android-ci-avd
      - run: ./gradlew connectedDebugAndroidTest


workflows:
  android-ci:
    jobs:
      - run-ui-tests