version: 2.1

orbs:
  android: circleci/android@2.5.0

jobs:
  run-ui-tests:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2022.06.2
    steps:
      - checkout
      - run:
          name: write keystore.properties file
          command: |
            touch keystore.properties
            echo $KEYSTORE_PROPERTIES_BASE64 | base64 --decode > keystore.properties
      - run:
          name: decode keystore
          command: |
            echo $KEYSTORE_BASE64 | base64 --decode > shotclockapp.jks
      - android/create-avd:
          avd-name: android-ci-avd
          system-image: system-images;android-31;default;x86_64
          install: true
      - android/start-emulator:
          avd-name: android-ci-avd
      - run:
          command: ./gradlew connectedDebugAndroidTest


workflows:
  android-ci:
    jobs:
      - run-ui-tests:
          filters:
            branches:
              only: master
