package jermaine.shotclockapp.utils

const val TEST_TAG_PAGER = "PAGER"
const val TEST_TAG_RESET = "RESET"
const val TEST_TAG_PLAY_PAUSE = "PLAY_PAUSE"
const val TEST_TAG_CLOCK_PAGE_24 = "CLOCK_PAGE_24"
const val TEST_TAG_CLOCK_PAGE_14 = "CLOCK_PAGE_14"
const val TEST_TAG_BUTTON_THEME = "BUTTON_THEME"
const val TEST_TAG_POPUP_THEME = "POPUP_THEME"
const val TEST_TAG_SETTINGS = "SETTINGS"
const val TEST_TAG_THEME_LIGHT = "THEME_LIGHT"
const val TEST_TAG_THEME_DARK = "THEME_DARK"
const val TEST_TAG_BUTTON_BACK = "BUTTON_BACK"